# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# don't forget to do this!
require 'open-uri'


User.destroy_all

guest = User.create(username: "guest", email: "guest@guest.com", password: "password123")
file = open('https://s3.us-east-2.amazonaws.com/middle-seeds/lasers.png')
guest.profile_picture.attach(io: file, filename: "lasers.png")

user1 = User.create(username: "Conley", email: "conley@email.com", password: "password")
user2 = User.create(username: "Oliver", email: "oliver@email.com", password: "password")
user3 = User.create(username: "Mashu", email: "mashu@email.com", password: "password")

Article.destroy_all

article1 = Article.create(topic_category: "Chinese Literature", author_id: user1.id, title: "Trauma in Mo Yan’s Frog", byline: "How the One-Child Policy Traumatized the Main Characters", body: "Upon finishing Mo Yan’s Frog, one is struck by its use of magical realism, the complex, and at times convoluted structure, and the use of far-fetched allegories. However, one of the most important aspects of the novel, that undercuts and encompasses many of the aforementioned aspects, is trauma. Frog plots spans several decades, decades where the most drastic policies were enacted by the Chinese Communist Party and tumultuous events transpired due to the Party’s rise. These events included the Great Leap Forward, the Cultural Revolution, the Reform and Opening-Up (改革开放), and the One-Child Policy. The One-Child Policy had tremendous implications for the everyday lives of the Chinese citizens, including the fictitious characters of Frog, and had vast implications for the narrative. These implications included Gugu and Little Lion being forced to carry out thousands of abortions, including the abortion of Tadpole’s baby, which led to Renmei’s death. The implications of these events reverberate throughout the book and end up shaping the plot’s development by causing a greater or lesser extent of trauma to be inflicted on three major characters: Gugu, Little Lion, and Tadpole.")
article2 = Article.create(topic_category: "English Literature", author_id: user2.id, title: "Postcolonial Theory and The Tempest", byline: "Does Cultural Freedom Equate “Political” Freedom?", body: "In William Shakespeare’s The Tempest, the island that the play takes place on is a mysterious place, a place inhabited by magical spirits and creatures, natives and visitors with visions of conquest, visions of power, visions of a utopian existence. The relationship between the natives of the islands and these visitors poses important questions about the place of postcolonial theory in the context of The Tempest. In light of these questions, I posit that, according to the framework laid out by postcolonial scholar Homi K. Bhabha in his essay “The Postcolonial and the Postmodern: The Question of Agency”, the island of The Tempest functions as an interstice – “the overlap and displacement of domains and difference” or “spaces [that] provide the terrain for elaborating strategies of selfhood” (Bhabha, “The Postcolonial” 765). By proving that the island is in fact a place where characters define themselves, or, as Bhabha would put it, “elaborate strategies of selfhood”, I will causally prove that the island is indeed an “in-between space,” or in other words, an interstice.")
article3 = Article.create(topic_category: "American Literature", author_id: user3.id, title: "Guilty Until Proven Innocent", byline: "Assumptions Made in Ubiquitous Applications of Surveillance", body: "In many novels and stories written in the past two centuries, surveillance has been a major fascination and focus. The novels and stories that have attracted my attention most acutely have been the novels and stories where there are examples of surveillance that is universally applied, surveillance applied without discretion. Two great examples of novels where surveillance is universally applied are 1984 by George Orwell and A Journal of the Plague Year by Daniel Defoe. Though the modes of surveillance and technologies used to inflict surveillance may be largely different in the two novels, they both provide insight into what assumptions are made by modes of surveillance which are meant to surveil everyone universally. I will focus most intently upon two specific modes of surveillance found within each text. Firstly, I will focus on the telescreen featured in 1984, and then I will focus on the Examiners’ surveillance methods in The Journal of the Plague Year. ")
article4 = Article.create(topic_category: "English Literature", author_id: user2.id, title: "The Ambiguity of Love in Shakespeare’s A Midsummer Night’s Dream ", byline: "Shakespeare's Early Conception of Love in The Early Works", body: "In A Midsummer Night’s Dream, there are a range of disparate characters that each come from different backgrounds. These characters are mostly grouped in pairs, with exceptions like the groups of fairies and the troupe of actors. The focus of this paper will be on the different groups of characters, groups which represent and perform different conceptions of love. For though Shakespeare has come to be known in the cultural imaginary as an expert on the subject, I argue that in A Midsummer Night’s Dream, Shakespeare does not necessarily leave the audience with a definitive answer regarding the definition of love. I argue, instead, that Shakespeare does provide multiple perspectives on love, each with its own downfalls and beautiful aspects, and by providing the audience with these, he does make a statement about love. This statement is understood by looking at the different conceptions of love performed in the play, as well as different conceptions of love performed in the plays with in the play.  ")
article5 = Article.create(topic_category: "American Literature", author_id: user1.id, title: "Social Media’s Downfall", byline: "A Persisting Schema of Exceptional Discipline", body: "In both Defoe’s account of the plague town and Foucault’s imagining of the plague town, there is a strict exercise of control over the inhabitants of the city. Some would argue that this strict control has been entirely weeded out from today’s society, that with the ever-brightening light of enlightenment, we have moved to a more subtle and efficient model of general surveillance or panopticism. However, I posit that though the methods of control have changed, elements of the plague town are still exhibited in modern day society, especially with regards to what Foucault would call “a schema of exceptional discipline” (Foucault 209). This is demonstrated by the modern world’s obsession with social media, particularly in regards to the control of speech present in modern day social media sites.")
article6 = Article.create(topic_category: "American Poetry", author_id: user1.id, title: "Temporality in the Poetry of Claudia Emerson", byline: " How Claudia Emerson Manipulates Time to Focus Reader’s Attention on Different Aspects of Narration ", body: "The problem of time, or paradox of time if you will, has plagued philosophers and deep thinkers for generations, indeed millennia. Construction of theory on time has been in progress from the days of Plato. It is Ricoeur, in his behemoth masterwork, Time and Narrative, that tackles this problem with gusto and whose analysis I will use in this essay. It is Ricoeur’s theory that I will use to analyze Claudia Emerson’s poetry from her book The Late Wife and Figure Studies. Claudia Emerson masterfully manipulates how time is expressed in the narration of the events she writes on, and this manipulation allows readers to come away with new conclusions and impressions.  ")
article7 = Article.create(topic_category: "Chinese Literature", author_id: user3.id, title: "Insincerity as the Pinnacle of Evil in Rescuing One of the Girls", byline: "Conceptions of Evil in 13th Century Chinese Theater", body: "Zhou She, while abominable and despicable, runs amok in a story filled with varying degrees of vice and evil. His actions, like beating his wife Song Yin-Zhang mercilessly and spending all his time in whorehouses while married, are clearly evil, yet I posit that Zhou She is used as a literary device, used to contrast to the lesser evils that every other character in the play act out. Stephen Owen gives a great description of this idea in the introduction to the play in his book The Anthology of Chinese Literature, “There is nothing pretty about [Guan Han-qing’s] world, and good is relative, measured against caricatures of evil” (Owen 745). In this paper I will examine the ways in which Zhou She is depicted as the pinnacle of evil in a world filled with misdeeds and morally questionable behavior, as well as illustrate that Rescuing One of the Girls’ conception of evil has more to do with insincerity than sexually promiscuous behavior.  ")
article8 = Article.create(topic_category: "American Literature", author_id: user2.id, title: "Syntactical Confusion in a Chapter of Darl’s in Faulkner’s As I Lay Dying", byline: " As I Lay Dying and Its Relation to an Ontological Dilemma", body: "Perhaps one of the most famous and confusing passages of William Faulkner’s As I Lay Dying comes in the opening half of the book, specifically found on pages 80-81. In these pages, the reader finds him or herself in the midst of a chapter narrated by the most clairvoyant and seemingly trustworthy of the many narrators, Darl. In this chapter, Darl recounts the finishing touches put on the coffin and the wagon that the family will take on their voyage to Jefferson. More than this, however, the reader finds a complex relationship between being and not being that Darl lays out in the form of a questioning of how one lays one down to sleep, and the complex relationship, perhaps only in Darl’s head, between the wagon, Jewel and Addie Bundren. Through the use of complex and convoluted sentence structure, seemingly nonsensical logical structures, and allusions to a different chronotope, Faulkner creates a passage that is at first confusing, but ultimately adds much to the themes of trauma and historical allusion.  ")
article9 = Article.create(topic_category: "English Literature", author_id: user2.id, title: "Ideology and the Body", byline: "What Slavoj Žižek Can Tell Us About Toni Morrison and Ralph Ellison in Beloved and Invisible Man ", body: "Toni Morrison’s Beloved and Ralph Ellison’s Invisible Man are both incredibly dense works that deal with many themes. They are masterful works of literature in their own rights. I, however, do not wish to dissect these works in their entirety. I instead wish to draw parallels between these two works by imposing a framework upon them. That framework is ideology, as outlined in the work of Dr. Slavoj Žižek. In so doing, perhaps the reader will come to a greater understanding of how these two novels work together to illuminate how humans respond physically to ideology and how ideology affects human physically, regardless of time-period or cultural landscape. ")

article1_cover_photo = open('https://s3.us-east-2.amazonaws.com/middle-seeds/frog.jpg')
article2_cover_photo = open('https://s3.us-east-2.amazonaws.com/middle-seeds/shakespeare.jpg')
article3_cover_photo = open('https://s3.us-east-2.amazonaws.com/middle-seeds/1984.jpg')
article4_cover_photo = open('https://s3.us-east-2.amazonaws.com/middle-seeds/midsummer.jpg')
article5_cover_photo = open('https://s3.us-east-2.amazonaws.com/middle-seeds/defoe.jpg')
article6_cover_photo = open('https://s3.us-east-2.amazonaws.com/middle-seeds/claudiaemerson.jpg')
article7_cover_photo = open('https://s3.us-east-2.amazonaws.com/middle-seeds/guanhanqing.jpg')
article8_cover_photo = open('https://s3.us-east-2.amazonaws.com/middle-seeds/faulkner.jpg')
article9_cover_photo = open('https://s3.us-east-2.amazonaws.com/middle-seeds/slavoj.jpg')

article1.cover_photo.attach(io: article1_cover_photo, filename: "frog.jpg")
article2.cover_photo.attach(io: article2_cover_photo, filename: "shakespeare.jpg")
article3.cover_photo.attach(io: article3_cover_photo, filename: "shakespeare.jpg")
article4.cover_photo.attach(io: article4_cover_photo, filename: "shakespeare.jpg")
article5.cover_photo.attach(io: article5_cover_photo, filename: "shakespeare.jpg")
article6.cover_photo.attach(io: article6_cover_photo, filename: "shakespeare.jpg")
article7.cover_photo.attach(io: article7_cover_photo, filename: "shakespeare.jpg")
article8.cover_photo.attach(io: article8_cover_photo, filename: "shakespeare.jpg")
article9.cover_photo.attach(io: article9_cover_photo, filename: "shakespeare.jpg")