# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)

# don't forget to do this!
require 'open-uri'


User.destroy_all

guest = User.create(username: "guest", email: "guest@guest.com", password: "password123")
file = open('https://s3.us-east-2.amazonaws.com/middle-seeds/lasers.png?response-content-disposition=inline&X-Amz-Security-Token=AgoGb3JpZ2luEKP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMiKAAihwj%2BsbF5vax4hFXXCyR8B4QdUc6EOMLGzZoN%2BDsyOb7des21MOC1QL0JZvbE02tZsh8KaeVm9X0mSEA%2BwVxKac9o6YJxsEF6P%2F98UgmnNQQKDwhMrKCSV8VhK0kkYIdU4BzTCaUsW7kpGBSM2ONT8B3ve4WuVB9EXLbeyUw4fUPod7Qi3KWnoT4lqQS%2BfjjVgnLpnedOgtEkpmS%2FXbSdnzSfmcG4FOQi8%2FUZcRrcIkp7Rfwxot4WCuO%2FDW0rm86iGRFFmInwyRaEEhJfkoKpQ4ZaRpHl7Gd6xjs7Qt1gYgMKoKA9ihjmmmguiQeOe5wMuFM8%2FM3vLCVS1TFT82dxsqpgIIjf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARABGgw1MjcwNDI0MDQ2NzQiDJFVNsReoIblFDHZJSr6AQ09QCYJXJpssDYMSC5pTmN1Z0WbRJMeNa2YBnnddPqDQ2RcwqFgValayEfDVmdsA4ObHF1C14kRXuKRPMs3K0fzvPqiNulzrsi0JavdsChn5zQCCvU6eRh4QX6G729vm8zfeoOlz9JYLCivUZ%2F2zvmI8jBzKAAJRCL6BFntpTUjeOivAFgrR45rcyS0QjI4LqtlkL16jFtLCOENXFbJCbkp4RKqWD%2BeiH5fMYrOrVsBdUTsnBD0J3W4hxNLr%2BxFUcziOQAIvibrPGyGd66Glj%2BOfKEz7SqTihP8vLdSX%2FqJTit5gwcmW3OHYl7%2F0p93h4kDhqIZZI3MHlUw1aDE5wU%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20190531T114356Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAXVNRM4FBHDI3EJDL%2F20190531%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Signature=7b31223d7443218c7179e308c1c547e413367fc984381add2324460d004ca2c1')
guest.profile_picture.attach(io: file, filename: "lasers.png")

Article.destroy_all

article1 = Article.create(topic_category: "Chinese Literature", author_id: guest.id, title: "Trauma in Mo Yan’s Frog", byline: "How the One-Child Policy Traumatized the Main Characters", body: "Upon finishing Mo Yan’s Frog, one is struck by its use of magical realism, the complex, and at times convoluted structure, and the use of far-fetched allegories. However, one of the most important aspects of the novel, that undercuts and encompasses many of the aforementioned aspects, is trauma. Frog plots spans several decades, decades where the most drastic policies were enacted by the Chinese Communist Party and tumultuous events transpired due to the Party’s rise. These events included the Great Leap Forward, the Cultural Revolution, the Reform and Opening-Up (改革开放), and the One-Child Policy. The One-Child Policy had tremendous implications for the everyday lives of the Chinese citizens, including the fictitious characters of Frog, and had vast implications for the narrative. These implications included Gugu and Little Lion being forced to carry out thousands of abortions, including the abortion of Tadpole’s baby, which led to Renmei’s death. The implications of these events reverberate throughout the book and end up shaping the plot’s development by causing a greater or lesser extent of trauma to be inflicted on three major characters: Gugu, Little Lion, and Tadpole.")
article2 = Article.create(topic_category: "English Literature", author_id: guest.id, title: "Postcolonial Theory and The Tempest", byline: "Does Cultural Freedom Equate “Political” Freedom?", body: "In William Shakespeare’s The Tempest, the island that the play takes place on is a mysterious place, a place inhabited by magical spirits and creatures, natives and visitors with visions of conquest, visions of power, visions of a utopian existence. The relationship between the natives of the islands and these visitors poses important questions about the place of postcolonial theory in the context of The Tempest. In light of these questions, I posit that, according to the framework laid out by postcolonial scholar Homi K. Bhabha in his essay “The Postcolonial and the Postmodern: The Question of Agency”, the island of The Tempest functions as an interstice – “the overlap and displacement of domains and difference” or “spaces [that] provide the terrain for elaborating strategies of selfhood” (Bhabha, “The Postcolonial” 765). By proving that the island is in fact a place where characters define themselves, or, as Bhabha would put it, “elaborate strategies of selfhood”, I will causally prove that the island is indeed an “in-between space,” or in other words, an interstice.")

article1_cover_photo = open('https://s3.us-east-2.amazonaws.com/middle-seeds/frog.jpg?response-content-disposition=inline&X-Amz-Security-Token=AgoGb3JpZ2luEKP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMiKAAihwj%2BsbF5vax4hFXXCyR8B4QdUc6EOMLGzZoN%2BDsyOb7des21MOC1QL0JZvbE02tZsh8KaeVm9X0mSEA%2BwVxKac9o6YJxsEF6P%2F98UgmnNQQKDwhMrKCSV8VhK0kkYIdU4BzTCaUsW7kpGBSM2ONT8B3ve4WuVB9EXLbeyUw4fUPod7Qi3KWnoT4lqQS%2BfjjVgnLpnedOgtEkpmS%2FXbSdnzSfmcG4FOQi8%2FUZcRrcIkp7Rfwxot4WCuO%2FDW0rm86iGRFFmInwyRaEEhJfkoKpQ4ZaRpHl7Gd6xjs7Qt1gYgMKoKA9ihjmmmguiQeOe5wMuFM8%2FM3vLCVS1TFT82dxsqpgIIjf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARABGgw1MjcwNDI0MDQ2NzQiDJFVNsReoIblFDHZJSr6AQ09QCYJXJpssDYMSC5pTmN1Z0WbRJMeNa2YBnnddPqDQ2RcwqFgValayEfDVmdsA4ObHF1C14kRXuKRPMs3K0fzvPqiNulzrsi0JavdsChn5zQCCvU6eRh4QX6G729vm8zfeoOlz9JYLCivUZ%2F2zvmI8jBzKAAJRCL6BFntpTUjeOivAFgrR45rcyS0QjI4LqtlkL16jFtLCOENXFbJCbkp4RKqWD%2BeiH5fMYrOrVsBdUTsnBD0J3W4hxNLr%2BxFUcziOQAIvibrPGyGd66Glj%2BOfKEz7SqTihP8vLdSX%2FqJTit5gwcmW3OHYl7%2F0p93h4kDhqIZZI3MHlUw1aDE5wU%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20190531T114526Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAXVNRM4FBHDI3EJDL%2F20190531%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Signature=afa51047213fb04609540c43770634959e2d53da60b6594e6598684678e34e74')
article2_cover_photo = open('https://s3.us-east-2.amazonaws.com/middle-seeds/shakespeare.jpg?response-content-disposition=inline&X-Amz-Security-Token=AgoGb3JpZ2luEKP%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FwEaCXVzLWVhc3QtMiKAAihwj%2BsbF5vax4hFXXCyR8B4QdUc6EOMLGzZoN%2BDsyOb7des21MOC1QL0JZvbE02tZsh8KaeVm9X0mSEA%2BwVxKac9o6YJxsEF6P%2F98UgmnNQQKDwhMrKCSV8VhK0kkYIdU4BzTCaUsW7kpGBSM2ONT8B3ve4WuVB9EXLbeyUw4fUPod7Qi3KWnoT4lqQS%2BfjjVgnLpnedOgtEkpmS%2FXbSdnzSfmcG4FOQi8%2FUZcRrcIkp7Rfwxot4WCuO%2FDW0rm86iGRFFmInwyRaEEhJfkoKpQ4ZaRpHl7Gd6xjs7Qt1gYgMKoKA9ihjmmmguiQeOe5wMuFM8%2FM3vLCVS1TFT82dxsqpgIIjf%2F%2F%2F%2F%2F%2F%2F%2F%2F%2FARABGgw1MjcwNDI0MDQ2NzQiDJFVNsReoIblFDHZJSr6AQ09QCYJXJpssDYMSC5pTmN1Z0WbRJMeNa2YBnnddPqDQ2RcwqFgValayEfDVmdsA4ObHF1C14kRXuKRPMs3K0fzvPqiNulzrsi0JavdsChn5zQCCvU6eRh4QX6G729vm8zfeoOlz9JYLCivUZ%2F2zvmI8jBzKAAJRCL6BFntpTUjeOivAFgrR45rcyS0QjI4LqtlkL16jFtLCOENXFbJCbkp4RKqWD%2BeiH5fMYrOrVsBdUTsnBD0J3W4hxNLr%2BxFUcziOQAIvibrPGyGd66Glj%2BOfKEz7SqTihP8vLdSX%2FqJTit5gwcmW3OHYl7%2F0p93h4kDhqIZZI3MHlUw1aDE5wU%3D&X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Date=20190531T114550Z&X-Amz-SignedHeaders=host&X-Amz-Expires=300&X-Amz-Credential=ASIAXVNRM4FBHDI3EJDL%2F20190531%2Fus-east-2%2Fs3%2Faws4_request&X-Amz-Signature=5e7fe57a0d63531b459c9035847ddabad384e8c6529fc4bbbbed90e0909693cd')

article1.cover_photo.attach(io: article1_cover_photo, filename: "frog.jpg")
article2.cover_photo.attach(io: article2_cover_photo, filename: "shakespeare.jpg")